<a href="https://colab.research.google.com/github/syedmahmoodiagents/Reinforce/blob/main/Value_iteration2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import gymnasium as gym

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [ ]:
env = gym.make('FrozenLake-v1', is_slippery=True)
n_states = env.observation_space.n
n_actions = env.action_space.n

In [ ]:
# Hyperparameters
gamma = 0.9   # Discount factor
theta = 1e-8   # Convergence threshold

In [ ]:
# Initialize value function (all zeros)
V = np.zeros(n_states)

In [ ]:
V

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
state = 14
action = 2
# V = np.zeros(n_states)
# -----------------
value = 0
for prob, next_state, reward, done in env.unwrapped.P[state][action]:
    value += prob * (reward + gamma * V[next_state]) # Bellman's Equation
print(value)

0.3333333333333333


In [ ]:
state = 14
n_actions = env.action_space.n
# action_values = []
for action in range(n_actions):
    value = 0
    for prob, next_state, reward, done in env.unwrapped.P[state][action]:
        value += prob * (reward + gamma * V[next_state]) # Bellman's Equation
    # action_values.append(value)
    print(action, ": ", value)

0 :  0.0
1 :  0.3333333333333333
2 :  0.3333333333333333
3 :  0.3333333333333333


In [ ]:
state = 14
n_actions = env.action_space.n # 4
action_values = []
for action in range(n_actions):
    value = 0
    for prob, next_state, reward, done in env.unwrapped.P[state][action]:
        value += prob * (reward + gamma * V[next_state]) # Bellman's Equation
    action_values.append(value)
    # print(value)
print(action_values)
best_action_value = max(action_values)
# print(best_action_value)

[np.float64(0.0), np.float64(0.3333333333333333), np.float64(0.3333333333333333), np.float64(0.3333333333333333)]


# Comparing the difference between the old values and new values

In [ ]:
n_states = env.observation_space.n
n_actions = env.action_space.n
V = np.zeros(n_states)
delta = 0
for state in range(n_states):
    # Compute the value of each action
    action_values = []
    for action in range(n_actions):
        value = 0
        for prob, next_state, reward, done in env.unwrapped.P[state][action]:
            value += prob * (reward + gamma * V[next_state]) # Bellman's Equation
        action_values.append(value)
    # Best action value for the state
    best_action_value = max(action_values)

    delta = max(delta, abs(V[state] - best_action_value))
    V[state] = best_action_value
    print(state, ": ", V, best_action_value)

0 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
1 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
2 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
3 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
4 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
5 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
6 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
7 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
8 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
9 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
10 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
11 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
12 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
13 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0
14 :  [0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.33333333 0.        ] 

In [ ]:
# max_iterations = 1000
V = np.zeros(n_states)
n_states = env.observation_space.n
n_actions = env.action_space.n
# Value Iteration
for i in range(1000):
    delta = 0
    for state in range(n_states):
        # Compute the value of each action
        action_values = []
        for action in range(n_actions):
            value = 0
            for prob, next_state, reward, done in env.unwrapped.P[state][action]:
                value += prob * (reward + gamma * V[next_state]) # Bellman's Equation
            action_values.append(value)

        # Best action value for the state
        best_action_value = max(action_values)
        listof_actions = np.argmax(action_values)
        # print(listof_actions)
        delta = max(delta, abs(V[state] - best_action_value))
        V[state] = best_action_value


    # Check for convergence
    if delta < theta: # theta is some threshold value
        print(f"Converged after {i + 1} iterations.")
        break

Converged after 324 iterations.
[0.54202581 0.49880303 0.47069551 0.4568515  0.55845085 0.
 0.35834799 0.         0.59179866 0.64307976 0.6152075  0.
 0.         0.7417204  0.86283741 0.        ]


# The Policy Making

In [ ]:
V

array([0.54202581, 0.49880303, 0.47069551, 0.4568515 , 0.55845085,
       0.        , 0.35834799, 0.        , 0.59179866, 0.64307976,
       0.6152075 , 0.        , 0.        , 0.7417204 , 0.86283741,
       0.        ])

In [ ]:
V[14]

np.float64(0.8628374086640991)

In [ ]:
# Derive policy from value function
policy = np.zeros(n_states, dtype=int)
for state in range(n_states):
    action_values = []
    for action in range(n_actions):
        value = 0
        for prob, next_state, reward, done in env.unwrapped.P[state][action]:
            value += prob * (reward + gamma * V[next_state])
        action_values.append(value)
    # Best action based on value function
    policy[state] = np.argmax(action_values)
print(policy)


[0 3 3 3 0 0 0 0 3 1 0 0 0 2 1 0]


In [ ]:
print(np.array(policy).reshape(4,4))

[[0 3 3 3]
 [0 0 0 0]
 [3 1 0 0]
 [0 2 1 0]]


In [ ]:
policy[0]

np.int64(0)

In [ ]:
# Display results
print(V.reshape(4, 4))
print(policy.reshape(4, 4))

[[0.54202581 0.49880303 0.47069551 0.4568515 ]
 [0.55845085 0.         0.35834799 0.        ]
 [0.59179866 0.64307976 0.6152075  0.        ]
 [0.         0.7417204  0.86283741 0.        ]]
[[0 3 3 3]
 [0 0 0 0]
 [3 1 0 0]
 [0 2 1 0]]


# Improved Full Code

In [ ]:
env.reset()
max_iterations = 1000
V = np.zeros(n_states)
policy = np.random.choice(n_states, size=n_states)
theta = 0.0000000001

n_states = env.observation_space.n
n_actions = env.action_space.n
# Value Iteration
for i in range(1000):
    delta = 0
    for state in range(n_states):
        # Compute the value of each action
        action_values = []
        for action in range(n_actions):
            value = 0
            for prob, next_state, reward, done in env.unwrapped.P[state][action]:
                value += prob * (reward + gamma * V[next_state]) # Bellman's Equation
            action_values.append(value)


        best_action_value = max(action_values)
        policy[state] = np.argmax(action_values)
        # print(listof_actions)
        delta = max(delta, abs(V[state] - best_action_value))
        V[state] = best_action_value


    # Check for convergence
    if delta < theta:
        print(f"Converged after {i + 1} iterations.")
        break


Converged after 110 iterations.


In [ ]:
policy

array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])

In [ ]:
policy[1]

np.int64(1)

# Inference

In [ ]:

# Test the policy
state, _ = env.reset()
env.render()
done = False
while not done:
    action = policy[state]
    state, reward, done, _, _ = env.step(action)
    env.render()

if reward == 1:
    print("Success!")
else:
    print("Failed!")


Failed!


/usr/local/lib/python3.12/dist-packages/gymnasium/envs/toy_text/frozen_lake.py:352: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("FrozenLake-v1", render_mode="rgb_array")
  gym.logger.warn(


In [ ]:
env.P


{0: {0: [(0.3333333333333333, 0, 0.0, False),
   (0.3333333333333333, 0, 0.0, False),
   (0.3333333333333333, 4, 0.0, False)],
  1: [(0.3333333333333333, 0, 0.0, False),
   (0.3333333333333333, 4, 0.0, False),
   (0.3333333333333333, 1, 0.0, False)],
  2: [(0.3333333333333333, 4, 0.0, False),
   (0.3333333333333333, 1, 0.0, False),
   (0.3333333333333333, 0, 0.0, False)],
  3: [(0.3333333333333333, 1, 0.0, False),
   (0.3333333333333333, 0, 0.0, False),
   (0.3333333333333333, 0, 0.0, False)]},
 1: {0: [(0.3333333333333333, 1, 0.0, False),
   (0.3333333333333333, 0, 0.0, False),
   (0.3333333333333333, 5, 0.0, True)],
  1: [(0.3333333333333333, 0, 0.0, False),
   (0.3333333333333333, 5, 0.0, True),
   (0.3333333333333333, 2, 0.0, False)],
  2: [(0.3333333333333333, 5, 0.0, True),
   (0.3333333333333333, 2, 0.0, False),
   (0.3333333333333333, 1, 0.0, False)],
  3: [(0.3333333333333333, 2, 0.0, False),
   (0.3333333333333333, 1, 0.0, False),
   (0.3333333333333333, 0, 0.0, False)]},
 2:

# One more Way

In [ ]:
env = gym.make("FrozenLake-v1", is_slippery=False)  # deterministic for clarity

# Initialize value function
V = np.zeros(env.observation_space.n)
gamma = 0.99
theta = 1e-6  # convergence threshold

while True:
    delta = 0
    for s in range(env.observation_space.n):
        v = V[s]
        action_values = []

        # For each action, calculate expected return
        for a in range(env.action_space.n):
            q_sa = 0
            for prob, next_state, reward, done in env.P[s][a]:
                q_sa += prob * (reward + gamma * V[next_state])
            action_values.append(q_sa)

        # Bellman optimality update
        V[s] = max(action_values)

        delta = max(delta, abs(v - V[s]))

    if delta < theta:
        break

print("Optimal Value Function:")
print(V)

# Derive optimal policy from value function
policy = np.zeros(env.observation_space.n, dtype=int)
for s in range(env.observation_space.n):
    action_values = []
    for a in range(env.action_space.n):
        q_sa = sum([prob * (reward + gamma * V[next_state])
                    for prob, next_state, reward, done in env.P[s][a]])
        action_values.append(q_sa)
    policy[s] = np.argmax(action_values)

print("\nOptimal Policy:")
print(policy)


Optimal Value Function:
[0.95099005 0.96059601 0.970299   0.96059601 0.96059601 0.
 0.9801     0.         0.970299   0.9801     0.99       0.
 0.         0.99       1.         0.        ]

Optimal Policy:
[1 2 1 0 1 0 1 0 2 1 1 0 0 2 2 0]


/usr/local/lib/python3.12/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.12/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [ ]:
import gymnasium

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [ ]:
gymnasium.envs.registry.keys()

dict_keys(['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'phys2d/CartPole-v0', 'phys2d/CartPole-v1', 'phys2d/Pendulum-v0', 'LunarLander-v3', 'LunarLanderContinuous-v3', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v3', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v1', 'CliffWalkingSlippery-v1', 'Taxi-v3', 'tabular/Blackjack-v0', 'tabular/CliffWalking-v0', 'Reacher-v2', 'Reacher-v4', 'Reacher-v5', 'Pusher-v2', 'Pusher-v4', 'Pusher-v5', 'InvertedPendulum-v2', 'InvertedPendulum-v4', 'InvertedPendulum-v5', 'InvertedDoublePendulum-v2', 'InvertedDoublePendulum-v4', 'InvertedDoublePendulum-v5', 'HalfCheetah-v2', 'HalfCheetah-v3', 'HalfCheetah-v4', 'HalfCheetah-v5', 'Hopper-v2', 'Hopper-v3', 'Hopper-v4', 'Hopper-v5', 'Swimmer-v2', 'Swimmer-v3', 'Swimmer-v4', 'Swimmer-v5', 'Walker2d-v2', 'Walker2d-v3', 'Walker2d-v4', 'Walker2d-v5', 'Ant-v2', 'Ant-v3', 'Ant-v4', 'Ant-v5', 'Humanoid-v2', 'Humanoid-v3', 